name: shift-bot
on:
  schedule:
    - cron: '0 5,11,17,23 * * *'
  workflow_dispatch:
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - run: |
          H=$(date -u +%H)
          if [ $H -ge 05 ] && [ $H -lt 11 ]; then echo "U=Bap" >> $GITHUB_ENV
          elif [ $H -ge 11 ] && [ $H -lt 17 ]; then echo "U=Darky" >> $GITHUB_ENV
          elif [ $H -ge 17 ] && [ $H -lt 23 ]; then echo "U=Tairo" >> $GITHUB_ENV
          else echo "U=Hrant" >> $GITHUB_ENV
          fi
      - run: curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"Current Turn ${{env.U}}\"}" https://discord.com/api/webhooks/1504734079222812744/2OwArDVSkZLf1_oJRMMs0ILjPuAm7ej3m7_Ryr2P9OLl9OdzNeZ2-WFhCXzQpqRFSaMf
